import {MEANING_TABLES} from "./mythic-constants.js";
import {ACTIONS_PART1, ACTIONS_PART2} from "./tables/actions.js";
import {DESCRIPTIONS_PART1, DESCRIPTIONS_PART2} from "./tables/descriptions.js";
import {
    ELEMENTS_ADVENTURE_TONE,
    ELEMENTS_ALIEN_SPECIES_DESCRIPTORS,
    ELEMENTS_ANIMAL_ACTIONS,
    ELEMENTS_ARMY_DESCRIPTORS,
    ELEMENTS_CAVERN_DESCRIPTORS,
    ELEMENTS_CHARACTER_ACTIONS_COMBAT,
    ELEMENTS_CHARACTER_ACTIONS_GENERAL,
    ELEMENTS_CHARACTER_APPEARANCE,
    ELEMENTS_CHARACTER_BACKGROUND,
    ELEMENTS_CHARACTER_CONVERSATIONS,
    ELEMENTS_CHARACTER_DESCRIPTORS,
    ELEMENTS_CHARACTER_IDENTITY,
    ELEMENTS_CHARACTER_MOTIVATIONS,
    ELEMENTS_CHARACTER_PERSONALITY,
    ELEMENTS_CHARACTER_SKILLS, ELEMENTS_CHARACTER_TRAITS_FLAWS,
    ELEMENTS_CHARACTERS, ELEMENTS_CITY_DESCRIPTORS
} from "./tables/elements.js";


export const MYTHIC_TABLES = {
    [MEANING_TABLES.ACTIONS]: ACTIONS_PART1,
    [MEANING_TABLES.ACTIONS_PART2]: ACTIONS_PART2,
    [MEANING_TABLES.DESCRIPTIONS]: DESCRIPTIONS_PART1,
    [MEANING_TABLES.DESCRIPTIONS_PART2]: DESCRIPTIONS_PART2,

    [MEANING_TABLES.ELEMENTS_ADVENTURE_TONE]: ELEMENTS_ADVENTURE_TONE,
    [MEANING_TABLES.ELEMENTS_ALIEN_SPECIES]: ELEMENTS_ALIEN_SPECIES_DESCRIPTORS,
    [MEANING_TABLES.ELEMENTS_ANIMAL_ACTIONS]: ELEMENTS_ANIMAL_ACTIONS,
    [MEANING_TABLES.ELEMENTS_ARMY_DESCRIPTORS]: ELEMENTS_ARMY_DESCRIPTORS,
    [MEANING_TABLES.ELEMENTS_CAVERN_DESCRIPTORS]: ELEMENTS_CAVERN_DESCRIPTORS,
    [MEANING_TABLES.ELEMENTS_CHARACTERS]: ELEMENTS_CHARACTERS,
    [MEANING_TABLES.ELEMENTS_CHARACTER_ACTIONS_COMBAT]: ELEMENTS_CHARACTER_ACTIONS_COMBAT,
    [MEANING_TABLES.ELEMENTS_CHARACTER_ACTIONS_GENERAL]: ELEMENTS_CHARACTER_ACTIONS_GENERAL,
    [MEANING_TABLES.ELEMENTS_CHARACTER_APPEARANCE]: ELEMENTS_CHARACTER_APPEARANCE,
    [MEANING_TABLES.ELEMENTS_CHARACTER_BACKGROUND]: ELEMENTS_CHARACTER_BACKGROUND,
    [MEANING_TABLES.ELEMENTS_CHARACTER_CONVERSATIONS]: ELEMENTS_CHARACTER_CONVERSATIONS,
    [MEANING_TABLES.ELEMENTS_CHARACTER_DESCRIPTORS]: ELEMENTS_CHARACTER_DESCRIPTORS,
    [MEANING_TABLES.ELEMENTS_CHARACTER_IDENTITY]: ELEMENTS_CHARACTER_IDENTITY,
    [MEANING_TABLES.ELEMENTS_CHARACTER_MOTIVATIONS]: ELEMENTS_CHARACTER_MOTIVATIONS,
    [MEANING_TABLES.ELEMENTS_CHARACTER_PERSONALITY]: ELEMENTS_CHARACTER_PERSONALITY,
    [MEANING_TABLES.ELEMENTS_CHARACTER_SKILLS]: ELEMENTS_CHARACTER_SKILLS,
    [MEANING_TABLES.ELEMENTS_CHARACTER_TRAITS_AND_FLAWS]: ELEMENTS_CHARACTER_TRAITS_FLAWS,
    [MEANING_TABLES.ELEMENTS_CITY_DESCRIPTORS]: ELEMENTS_CITY_DESCRIPTORS,


};